import './styles/globals.scss'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Header from "@/components/layout-components/Header/Header";
import {AntdRegistry} from "@ant-design/nextjs-registry";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Skill Tester',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Header/>
        <main className="content">
            <AntdRegistry>
                {children}
            </AntdRegistry>
        </main>
        </body>
        </html>
    )
}
